stages:
  - build
  - test
  - deploy

default:
  image: docker:dind
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASS} ${REGISTRY_URL}

variables:
  IMAGE_PATH: ${REGISTRY_URL}
  VERSION: v1.0.1

result-build-job:
  stage: build
  image: docker:dind
  script:
    # - cd result
    - docker build -t ${IMAGE_PATH}/multirepo-result:$CI_COMMIT_SHORT_SHA .
    - docker push ${IMAGE_PATH}/multirepo-result:$CI_COMMIT_SHORT_SHA

result-test-image:
  stage: test
  needs: ["result-build-job"]
  script:
    - docker pull ${IMAGE_PATH}/multirepo-result:$CI_COMMIT_SHORT_SHA
    - echo "result image test"
    - docker tag ${IMAGE_PATH}/multirepo-result:$CI_COMMIT_SHORT_SHA ${IMAGE_PATH}/multirepo-result:${VERSION}
    - docker push ${IMAGE_PATH}/multirepo-result:${VERSION}

deploy-to-pre-product:
  stage: deploy
  # needs: ["result-service-image-scan"]z
  trigger:
    project: ista/multirepo-result
    branch: main
